"""add 2fa temp fields and backup codes

Revision ID: 0ab2969563f5
Revises: d1fdc87da3c9
Create Date: 2025-11-25 01:42:47.174977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab2969563f5'
down_revision: Union[str, Sequence[str], None] = 'd1fdc87da3c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
