"""add 2fa fields and backup codes

Revision ID: d1fdc87da3c9
Revises: d5b34f323ca5
Create Date: 2025-11-24 13:58:11.972110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1fdc87da3c9'
down_revision: Union[str, Sequence[str], None] = 'd5b34f323ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'sku_id')
    op.add_column('orders', sa.Column('delivery_type', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_status', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_tracking', sa.String(), nullable=True))
    op.add_column('roles', sa.Column('is_system', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'is_system')
    op.drop_column('orders', 'delivery_tracking')
    op.drop_column('orders', 'delivery_status')
    op.drop_column('orders', 'delivery_type')
    op.add_column('order_items', sa.Column('sku_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
