"""add 2fa fields and backup codes

Revision ID: d5b34f323ca5
Revises: 96a60174218e
Create Date: 2025-11-24 02:30:05.298990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5b34f323ca5'
down_revision: Union[str, Sequence[str], None] = '96a60174218e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_codes_id'), 'backup_codes', ['id'], unique=False)
    op.add_column('users', sa.Column('totp_secret_temp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('failed_2fa_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_2fa_attempt_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_2fa_attempt_at')
    op.drop_column('users', 'failed_2fa_attempts')
    op.drop_column('users', 'totp_secret_temp')
    op.drop_index(op.f('ix_backup_codes_id'), table_name='backup_codes')
    op.drop_table('backup_codes')
    # ### end Alembic commands ###
